local M = {}

M.base46 = {
  theme = "flexoki-light",
  theme_toggle = { "flexoki", "flexoki-light" },
  transparency = false,
  favorite_themes = { "catppuccin-latte", "default-dark", "everblush", "flexoki", "gruvbox", "gruvchad", "yoru", "flexoki-light" },
}

M.ui = {
  cmp = { style = "default" },
  telescope = { style = "borderless" },
  statusline = {
    enabled = true,
    theme = "default",
    separator_style = "round",
  },
  tabufline = {
    enabled = true,
    lazyload = true,
    treeOffsetFt = "neo-tree",
  },
}

M.nvdash = {
  load_on_startup = true,
  header = {
    "                              ",
    "  ▄▄         ▄ ▄▄▄▄▄▄▄       ",
    "  ▀███▄     ▄██ █████▀        ",
    "  ██▄▀███▄   ███             ",
    "  ███  ▀███▄ ███             ",
    "  ███    ▀██ ███             ",
    "  ███      ▀ ███             ",
    "  ▀██ █████▄▀█▀▄██████▄      ",
    "    ▀ ▀▀▀▀▀▀▀ ▀▀▀▀▀▀▀▀▀▀    ",
    "                              ",
    "         ~ TethheTwo ~        ",
    "                              ",
  },
  buttons = {
    { txt = "  Find File", keys = "ff", cmd = "Telescope find_files" },
    { txt = "  Recent Files", keys = "fr", cmd = "Telescope oldfiles" },
    { txt = "󰈭  Find Word", keys = "fw", cmd = "Telescope live_grep" },
    { txt = "  Mason", keys = "cm", cmd = "Mason" },
    { txt = "󰒲  Lazy", keys = "lz", cmd = "Lazy" },
    { txt = "󱥚  Themes", keys = "th", cmd = "ThemeSelect" },
    { txt = "  Quit", keys = "q", cmd = "qa" },
  },
  keymaps = {
    { category = "Navigation" },
    { keys = "j / k", desc = "Move cursor (smart wrap)" },
    { keys = "<C-h/j/k/l>", desc = "Navigate windows" },
    { keys = "<C-Up/Down/Left/Right>", desc = "Resize windows" },
    { keys = "]t / [t", desc = "Next / prev tabpage" },
    { category = "Buffers" },
    { keys = "<Tab> / <S-Tab>", desc = "Next / prev buffer" },
    { keys = "<leader>x", desc = "Close buffer" },
    { category = "Files" },
    { keys = "<leader>e", desc = "File explorer" },
    { keys = "<leader>ff", desc = "Find files" },
    { keys = "<leader>fg", desc = "Live grep (search)" },
    { keys = "<leader>fr", desc = "Recent files" },
    { keys = "<leader>fb", desc = "Buffers list" },
    { keys = "<leader>fh", desc = "Help tags" },
    { keys = "<leader>fk", desc = "Keymaps (telescope)" },
    { keys = "<leader>fs", desc = "LSP symbols" },
    { category = "LSP" },
    { keys = "gd", desc = "Go to definition" },
    { keys = "K", desc = "Hover documentation" },
    { keys = "gi", desc = "Go to implementation" },
    { keys = "gr", desc = "Find references" },
    { keys = "<leader>D", desc = "Type definition" },
    { keys = "<C-k>", desc = "Signature help" },
    { keys = "<leader>rn", desc = "Rename symbol" },
    { keys = "<leader>ca", desc = "Code action" },
    { keys = "<leader>d", desc = "Diagnostic float" },
    { keys = "[d / ]d", desc = "Prev / next diagnostic" },
    { keys = "<leader>q", desc = "Diagnostics to loclist" },
    { category = "Git" },
    { keys = "]c / [c", desc = "Next / prev hunk" },
    { keys = "<leader>hs", desc = "Stage hunk" },
    { keys = "<leader>hr", desc = "Reset hunk" },
    { keys = "<leader>hp", desc = "Preview hunk diff" },
    { keys = "<leader>hb", desc = "Blame line" },
    { keys = "<leader>tb", desc = "Toggle line blame" },
    { keys = "<leader>hd", desc = "Diff this file" },
    { category = "Terminal" },
    { keys = "<C-\\>", desc = "Toggle terminal" },
    { keys = "<leader>tl", desc = "Lazygit" },
    { category = "Edit" },
    { keys = "<A-j> / <A-k>", desc = "Move line up / down" },
    { keys = "<C-s>", desc = "Save file" },
    { keys = "<leader>w", desc = "Save" },
    { keys = "<leader>q", desc = "Quit" },
    { keys = ";", desc = "Enter command mode" },
    { keys = "<Esc>", desc = "Clear search highlight" },
    { category = "Completion (insert)" },
    { keys = "<Tab> / <S-Tab>", desc = "Select next / prev" },
    { keys = "<C-j> / <C-k>", desc = "Select next / prev" },
    { keys = "<CR>", desc = "Accept completion" },
    { keys = "<C-b> / <C-f>", desc = "Scroll doc down / up" },
  },
}

M.term = {
  startinsert = true,
}

return M
